---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-system
resources:
  - ./../../base
  - ./../../management
  - user-secret.yaml
patches:
  - target:
      kind: RabbitmqCluster
    patch: |-
      - op: add
        path: "/spec/rabbitmq/additionalPlugins/-"
        value: rabbitmq_management
    # - op: add
    #   path: "/spec/rabbitmq/additionalPlugins/-"
    #   value: rabbitmq_mqtt
    # - op: add
    #   path: "/spec/rabbitmq/additionalPlugins/-"
    #   value: rabbitmq_shovel
    # - op: add
    #   path: "/spec/rabbitmq/additionalPlugins/-"
    #   value: rabbitmq_shovel_management
