apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-local-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: "kube.local Root CA"
  secretName: kube-local-root-ca
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-local
  usages:
    - cert sign
    - crl sign
    - digital signature
