---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/rabbitmq/cluster-operator/releases/download/v2.19.1/cluster-operator.yml
  - ./topology-operator
patches:
  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/resources" 
        value:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 20Mi
    target:
      kind: Deployment
      name: rabbitmq-cluster-operator
      namespace: rabbitmq-system
  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/resources" 
        value:
          limits:
            cpu: 100m
            memory: 75Mi
          requests:
            cpu: 10m
            memory: 20Mi
    target:
      kind: Deployment
      name: messaging-topology-operator
      namespace: rabbitmq-system
